name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nim: [1.6.x, 2.0.x, 2.2.4, 2.2.x, devel]
        exclude:
          - os: windows-latest
            nim: devel
    steps:
    - uses: actions/checkout@v7
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      run: |
        nimble install -y --depsOnly
    - name: Run Tests
      run: |
        nimble test
